### ISSUE TITLE
test bug

### ISSUE THREAD

**Issue by ZachyFoxx** [SolteraGG/StickyAPI#22]
**Describe the bug**

**To Reproduce**
1. Type '...'
3. See error

**Expected behavior**

**Console Logs**
If applicable, give a pastebin link to the console error related to LolBans

**Context:**
 - OS: [e.g. Linux]
 - Server Version [e.g. 1.14.4]
 - Plugin Version [e.g. 1.0.3]

**Additional context**

**Comment by jcxldn** [comment]
`LolBans`
