### ISSUE TITLE
Javadocs don't generate for Lombok annotations

### ISSUE THREAD

**Issue by kaylendog** [SolteraGG/StickyAPI#4]
**Describe the bug**
Javadocs are not generated for Lombok-annotated fields & methods project-wide.

**To Reproduce**
1. Generate Javadocs

**Expected behavior**
Javadocs should be copied over to their respective generated methods as per the Lombok documentation.
> NEW in lombok v1.12.0: javadoc on the field will now be copied to generated getters and setters. [Link](https://projectlombok.org/features/GetterSetter)

**Additional context**
Looks like we need to run [delombok](https://projectlombok.org/features/delombok) - requires using the `lombok.jar` or finding a Gradle plugin that does this for us? Solutions I've found are using Ant, and I don't really want to include ANOTHER step during build.

**Comment by aakatz3** [comment]
https://stackoverflow.com/questions/24997441/delombok-using-gradle

**Comment by jcxldn** [comment]
https://plugins.gradle.org/search?term=delombok ?
