### ISSUE TITLE
Gradle module refactor

### ISSUE THREAD

**Issue by kaylendog** [SolteraGG/StickyAPI#94]
**Describe the solution you'd like**
Refactor StickyAPI into independent Gradle modules. These can be included in a plugin jar as required, rather than shading the entire API. It would also have benefits from a development perspective - less Git conflicts, easier code management etc.

Proposed modules to add:
- `bukkit` - Bukkit-related utilites, only works with the Craftbukkit runtime.
- `bungee` - Bungee-related utilites, only works with the Bungeecord runtime.
- `common` - Common utilites shared between the former, works without a specific runtime.
- `example` - An example module containing the required build files for people to copy - is not included in the final jar.
- `translation` - Module for dealing with string interpolations given configuration.
- `worlds` - Depending on its size, module for world management & templating.
- `math` - Math library and utilities.
- `config` - Library for better config management, with support for YAML, JSON, and TOML.

**Comment by Prouser123** [comment]
> * `example` - An example module containing the required build files for people to copy - is not included in the final jar

What would this include?

**Comment by kaylendog** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Gradle module refactor](https://trello.com/c/R3wYoZM9/1-gradle-module-refactor)
